### ISSUE TITLE
support for v17

### ISSUE THREAD

**Issue by draylegend** [railwayapp-templates/angular-starter#1]
I've updated this template to v17, but the link to the app doesn't work although it deploys successfully.

This is the new dist folder structure after updating the ng to v17:

![image](https://github.com/railwayapp-templates/angular-starter/assets/16114644/a37c1f02-c7d1-42d3-94e7-a1102e48a737)

How to configure the Caddyfile so that the app gets served?

[Repo](https://github.com/draylegend/ng-railway)

**Comment by brody192** [comment]
ah the update must have overwritten the `outputPath` in your angular.json file, make sure it's set back to `dist`

**Comment by brody192** [comment]
but that's a good reminder for me, I will be upgrading this template to v17

**Comment by draylegend** [comment]
removed the entire nixpacks and caddy configuration from the repo and added the following envs

![image](https://github.com/railwayapp-templates/angular-starter/assets/16114644/a02c855a-7037-45da-9300-55a053a307b4)

[ng-railway repo](https://github.com/draylegend/ng-railway)
