### ISSUE TITLE
Angular Universal/SSR

### ISSUE THREAD

**Issue by hampton1122** [railwayapp-templates/angular-starter#2]
Can this be used for Angular Universal and SSR?

**Comment by brody192** [comment]
Nope, this template is only for a client-side rendered angular 17 app, will try my hand at creating a separate server-side rendered angular 17 template instead!

**Comment by brody192** [comment]
@hampton1122 - made a template for ssr angular 17, that can be found here: [https://railway.app/template/A5t142](https://railway.app/template/A5t142)
but this is the information you need to get your pre-existing project working on Railway:
[https://github.com/brody192/angular-starter-ssr](https://github.com/brody192/angular-starter-ssr?tab=readme-ov-file#-what-was-changed-from-the-default-angular-17-server-side-rendered-example)

if you need any more help, please open a #help thread on our discord server!

**Comment by hampton1122** [comment]
Thanks so much for jumping on this. I love this community!
